package hotspot.user.kafka.domain;

public enum NotificationType {
    SINGLE_USAGE_THRESHOLD_50,
    SINGLE_USAGE_THRESHOLD_30,
    SINGLE_USAGE_THRESHOLD_10,
    SINGLE_USAGE_EXHAUSTED,
    FAMILY_USAGE_THRESHOLD_50,
    FAMILY_USAGE_THRESHOLD_30,
    FAMILY_USAGE_THRESHOLD_10,
    FAMILY_USAGE_EXHAUSTED,
    PRESENT_USAGE_THRESHOLD_50,
    PRESENT_USAGE_THRESHOLD_30,
    PRESENT_USAGE_THRESHOLD_10,
    PRESENT_USAGE_EXHAUSTED,
    TIME_WINDOW_POLICY_APPLIED,
    TIME_WINDOW_POLICY_RELEASED,
    IMMEDIATE_BLOCK_APPLIED,
    IMMEDIATE_BLOCK_RELEASED,
    SERVICE_ACCESS_BLOCKED,
    SERVICE_ACCESS_RELEASED,
    PRESENT_DATA
}
