spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 30s
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 1s
