package hotspot.user.weeklyReport.domain.mapper;

import hotspot.user.common.util.UsageCalculator;
import hotspot.user.weeklyReport.controller.response.WeeklyReportResponse;
import hotspot.user.weeklyReport.domain.WeeklyReport;

public class WeeklyReportMapper {
    public static WeeklyReportResponse toWeeklyReportResponse(WeeklyReport domain) {
        return WeeklyReportResponse.builder()
                .subId(domain.getSubId())
                .name(domain.getName())
                .weekStartDate(domain.getWeekStartDate())
                .weekEndDate(domain.getWeekEndDate())
                .overview(WeeklyReportResponse.Overview.builder()
                        .scoreData(WeeklyReportResponse.ScoreDataResponse.builder()
                                .totalScore(domain.getScoreData().totalScore())
                                .scoreLevel(domain.getScoreData().scoreLevel().name())
                                .scoreDiff(domain.getScoreData().scoreDiff())
                                .reason(domain.getScoreData().reasons().stream()
                                        .map(r -> WeeklyReportResponse.ScoreReasonResponse.builder()
                                                .value(r.value())
                                                .exp(r.reason())
                                                .build())
                                        .toList())
                                .build())
                        .tags(domain.getTags())
                        .build())
                .dailyUsage(WeeklyReportResponse.DailyUsage.builder()
                        .weekdayAvg(UsageCalculator.kbToGb(domain.getSummaryData().dailySummary().weekdayAvg()))
                        .weekdayAvgDiff(UsageCalculator.kbToGb(domain.getSummaryData().dailySummary().weekdayAvgDiff()))
                        .weekdayAvgChangeRate(domain.getSummaryData().dailySummary().weekdayAvgChangeRate())
                        .weekendAvg(UsageCalculator.kbToGb(domain.getSummaryData().dailySummary().weekendAvg()))
                        .weekendAvgDiff(UsageCalculator.kbToGb(domain.getSummaryData().dailySummary().weekendAvgDiff()))
                        .weekendAvgChangeRate(domain.getSummaryData().dailySummary().weekendAvgChangeRate())
                        .ai_feedback(domain.getAiFeedback().summaryText().daily())
                        .dailyUsageList(domain.getUsageListData().dailyUsageList().stream()
                                .map(d -> WeeklyReportResponse.DailyUsageItem.builder()
                                        .day(d.day())
                                        .lastWeek(UsageCalculator.kbToGb(d.lastWeek()))
                                        .thisWeek(UsageCalculator.kbToGb(d.thisWeek()))
                                        .build())
                                .toList())
                        .build())
                .hourlyUsage(WeeklyReportResponse.HourlyUsage.builder()
                        .lateNightUsage(UsageCalculator.kbToGb(
                                domain.getSummaryData().hourlySummary().lateNightUsage()))
                        .lateNightUsageDiff(UsageCalculator.kbToGb(
                                domain.getSummaryData().hourlySummary().lateNightUsageDiff()))
                        .lateNightUsageChangeRate(domain.getSummaryData().hourlySummary().lateNightUsageChangeRate())
                        .studyTimeUsage(UsageCalculator.kbToGb(
                                domain.getSummaryData().hourlySummary().studyTimeUsage()))
                        .studyTimeUsageDiff(UsageCalculator.kbToGb(
                                domain.getSummaryData().hourlySummary().studyTimeUsageDiff()))
                        .studyTimeUsageChangeRate(domain.getSummaryData().hourlySummary().studyTimeUsageChangeRate())
                        .ai_feedback(domain.getAiFeedback().summaryText().hourly())
                        .hourlyUsageList(domain.getUsageListData().hourlyUsageList().stream()
                                .map(h -> WeeklyReportResponse.HourlyUsageItem.builder()
                                        .hour(h.hour())
                                        .lastWeek(UsageCalculator.kbToGb(h.lastWeek()))
                                        .thisWeek(UsageCalculator.kbToGb(h.thisWeek()))
                                        .isLateNight(h.isLateNight())
                                        .isStudyTime(h.isStudyTime())
                                        .build())
                                .toList())
                        .build())
                .categoryUsageList(WeeklyReportResponse.CategoryUsageList.builder()
                        .ai_feedback(domain.getAiFeedback().summaryText().category())
                        .thisWeek(domain.getUsageListData().categoryUsageList().thisWeek().stream()
                                .map(c -> WeeklyReportResponse.CategoryUsageItem.builder()
                                        .category(c.category())
                                        .usage(UsageCalculator.kbToGb(c.usage()))
                                        .percent(c.percent())
                                        .build())
                                .toList())
                        .lastWeek(domain.getUsageListData().categoryUsageList().lastWeek().stream()
                                .map(c -> WeeklyReportResponse.CategoryUsageItem.builder()
                                        .category(c.category())
                                        .usage(UsageCalculator.kbToGb(c.usage()))
                                        .percent(c.percent())
                                        .build())
                                .toList())
                        .comparison(domain.getUsageListData().categoryUsageList().comparison().stream()
                                .map(c -> WeeklyReportResponse.CategoryComparison.builder()
                                        .category(c.category())
                                        .changeRate(c.changeRate())
                                        .build())
                                .toList())
                        .build())
                .final_feedback(WeeklyReportResponse.FinalFeedback.builder()
                        .parent(domain.getAiFeedback().feedback().toParent())
                        .child(domain.getAiFeedback().feedback().toChild())
                        .policyRecommendList(domain.getAiFeedback().policyRecommendList().stream()
                                .map(p -> WeeklyReportResponse.PolicyRecommend.builder()
                                        .title(p.title())
                                        .description(p.description())
                                        .reason(p.reason())
                                        .build())
                                .toList())
                        .build())
                .build();
    }
}
