name: USER-BE CD (dev)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      CLUSTER: hotspot-cluster
      SERVICE: UserServiceStack-UserServiceDFC9364A-WzK5MyZC3ANk
      TASK_DEF_NAME: UserServiceStackUserTaskDef699DB911
      ECR_REPO: hotspot-user
      CONTAINER_NAME: UserContainer

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            -t 121834501390.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG \
            --push .

      - name: Get Current Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition $TASK_DEF_NAME \
            --query taskDefinition > task-def.json

      - name: Render New Task Definition
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_URI=121834501390.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG

          jq --arg IMAGE "$IMAGE_URI" \
            '.containerDefinitions[0].image = $IMAGE
             | del(.taskDefinitionArn)
             | del(.revision)
             | del(.status)
             | del(.requiresAttributes)
             | del(.compatibilities)
             | del(.registeredAt)
             | del(.registeredBy)' \
            task-def.json > new-task-def.json

      - name: Register New Revision
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster $CLUSTER \
            --service $SERVICE \
            --task-definition $TASK_DEF_NAME
